# Generated by Django 6.0.3 on 2026-03-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SklepApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dostepny',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cena',
            new_name='price',
        ),
    ]
