# Generated by Django 6.0.3 on 2026-06-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SklepApp', '0007_order_city_order_full_name_order_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Przelew', 'Przelew'), ('Za pobraniem', 'Za pobraniem'), ('BLIK', 'BLIK')], default='Przelew', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Nowe', 'Nowe'), ('W realizacji', 'W realizacji'), ('Wysłane', 'Wysłane'), ('Dostarczone', 'Dostarczone'), ('Anulowane', 'Anulowane')], default='Nowe', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
