from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('product/<int:product_id>/', views.item_details, name='item_details'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart, name='cart'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('kontakt/', views.kontakt_view, name='kontakt'),
    path('panel/', views.panel_view, name='panel'),
    path('check-username/', views.check_username, name='check_username'),
    path('increase/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('panel/', views.panel_view, name='panel'),
    path('panel/dane/', views.user_data_view, name='user_data'),
    path('panel/zamowienia/', views.user_orders_view, name='user_orders'),
    path('panel/zamowienia/<int:order_id>/', views.order_detail_view, name='order_detail'),
    path('panel/ulubione/', views.user_favorites_view, name='user_favorites'),
    path('panel/adresy/', views.user_addresses_view, name='user_addresses'),
    path('panel/ustawienia/', views.user_settings_view, name='user_settings'),
    path('reset-hasla/',auth_views.PasswordResetView.as_view(template_name='password_reset.html',email_template_name='password_reset_email.html',success_url='/reset-hasla/wyslano/'),name='password_reset'),
    path('reset-hasla/wyslano/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('reset-hasla/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url='/reset-hasla/gotowe/'),name='password_reset_confirm'),
    path('reset-hasla/gotowe/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('zamowienie/<int:order_id>/gotowe/', views.order_success_view, name='order_success'),
    path('panel/usun-konto/', views.delete_account_view, name='delete_account'),
    path('panel/zamowienia/<int:order_id>/anuluj/', views.cancel_order_view, name='cancel_order'),
]